<a href="https://colab.research.google.com/github/Deepa-chaurasiya01/BreastCancer-Prediction/blob/main/Breast_Cancer_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [122]:
import numpy as np

`import sklearn.datasets` :- as we're going to get the dataset we don't need to download it,  to get the dataset load it.

In [123]:
import sklearn.datasets

In [124]:
breast_cancer = sklearn.datasets.load_breast_cancer()

In [125]:
breast_cancer

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry\n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        worst/largest values) of these features were computed for each image,\n        resulting in 30 features.

from sklearn import datasets 
iris=datasets.load_iris()
X = iris.data

In [126]:
X = breast_cancer.data

Y = breast_cancer.target

In [127]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [128]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [129]:
X.shape , Y.shape

((569, 30), (569,))

In [130]:
import pandas as pd


In [131]:
data = pd.DataFrame(breast_cancer.data, columns = breast_cancer.feature_names)

In [132]:
data['class'] = breast_cancer.target

In [133]:
data.head()

mean radius  mean texture  ...  worst fractal dimension  class
0        17.99         10.38  ...                  0.11890      0
1        20.57         17.77  ...                  0.08902      0
2        19.69         21.25  ...                  0.08758      0
3        11.42         20.38  ...                  0.17300      0
4        20.29         14.34  ...                  0.07678      0

[5 rows x 31 columns]

In [134]:
data.describe()

mean radius  mean texture  ...  worst fractal dimension       class
count   569.000000    569.000000  ...               569.000000  569.000000
mean     14.127292     19.289649  ...                 0.083946    0.627417
std       3.524049      4.301036  ...                 0.018061    0.483918
min       6.981000      9.710000  ...                 0.055040    0.000000
25%      11.700000     16.170000  ...                 0.071460    0.000000
50%      13.370000     18.840000  ...                 0.080040    1.000000
75%      15.780000     21.800000  ...                 0.092080    1.000000
max      28.110000     39.280000  ...                 0.207500    1.000000

[8 rows x 31 columns]

In [135]:
data['class'].value_counts()

1    357
0    212
Name: class, dtype: int64

In [136]:
breast_cancer.target_names  # as we know the taget name is already specified that's why this names

array(['malignant', 'benign'], dtype='<U9')

0 is for malignent and 1 is for benign

In [137]:
data.groupby('class').mean()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
class                             ...                                         
0        17.462830     21.604906  ...        0.323468                 0.091530
1        12.146524     17.914762  ...        0.270246                 0.079442

[2 rows x 30 columns]

### Train and Test Split

In [138]:
from sklearn.model_selection import train_test_split

In [139]:
# train_test_split?

 test_size ---> to specify the % of test data needed

In [140]:
X_train, X_test, Y_train, Y_test = train_test_split( X, Y, test_size=0.1, random_state=30)

In [141]:
Y.shape ,Y_train.shape, Y_test.shape

((569,), (512,), (57,))

In [142]:
Y.mean(), Y_test.mean(), Y_test.mean()

(0.6274165202108963, 0.6491228070175439, 0.6491228070175439)

 stratify=y ; for correct distribution of data as of the original data
 
 will make sure that your random split has 25% of 0 's and 75% of 1 's.

In [143]:
X_train, X_test, Y_train, Y_test = train_test_split( X, Y, test_size=0.1, stratify =Y)

In [144]:
Y.mean(), Y_test.mean(), Y_train.mean()

(0.6274165202108963, 0.631578947368421, 0.626953125)

As we can both are almost similar

random_state ---> specific split of the data each value of random_state splits the data differently

In [145]:
X_train, X_test, Y_train, Y_test = train_test_split( X, Y, test_size=0.1, stratify =Y, random_state=1)

In [146]:
X.mean(), X_test.mean(), X_train.mean()

(61.890712339519624, 67.04963097269005, 61.31637960106119)

In [147]:
X_train

array([[1.490e+01, 2.253e+01, 1.021e+02, ..., 2.475e-01, 2.866e-01,
        1.155e-01],
       [1.205e+01, 1.463e+01, 7.804e+01, ..., 6.548e-02, 2.747e-01,
        8.301e-02],
       [1.311e+01, 1.556e+01, 8.721e+01, ..., 1.986e-01, 3.147e-01,
        1.405e-01],
       ...,
       [1.258e+01, 1.840e+01, 7.983e+01, ..., 8.772e-03, 2.505e-01,
        6.431e-02],
       [1.349e+01, 2.230e+01, 8.691e+01, ..., 1.282e-01, 2.871e-01,
        6.917e-02],
       [1.919e+01, 1.594e+01, 1.263e+02, ..., 1.777e-01, 2.443e-01,
        6.251e-02]])

**Logisitic Regression**

In [148]:
from sklearn.linear_model import LogisticRegression

In [149]:
classifire = LogisticRegression(max_iter=3000) #loading the reg model to the variable classifer

In [150]:
#  training the model on training data
classifire.fit(X_train , Y_train)

LogisticRegression(max_iter=3000)

# Evaluate

In [151]:
#  import accuracy score
from sklearn.metrics import accuracy_score

In [152]:
prediction_on_train = classifire.predict(X_train)
accuracy = accuracy_score(Y_train, prediction_on_train)

In [153]:
print('Accuracy on train data : ', accuracy)

Accuracy on train data :  0.958984375


### 95% on traing data

In [154]:
#  we need to check the test data as well
prediction_on_test = classifire.predict(X_test)
accuracy_test = accuracy_score(Y_test, prediction_on_test)

In [155]:
print('Accuracy of test :' ,accuracy_test) # generally the accuracy of test data will be less than the train data

Accuracy of test : 0.9473684210526315


### 94% on testing data

## Detection whether the Patient has Breast Cancer in Benign or in Malignant stage

In [156]:
input_data = (17.99,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,0.2419,0.07871,1.095,0.9053,8.589,153.4,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189)

change it to numpy array in oreder to make predictions

In [157]:
ip_array = np.asarray(input_data)
input_data

(17.99,
 10.38,
 122.8,
 1001,
 0.1184,
 0.2776,
 0.3001,
 0.1471,
 0.2419,
 0.07871,
 1.095,
 0.9053,
 8.589,
 153.4,
 0.006399,
 0.04904,
 0.05373,
 0.01587,
 0.03003,
 0.006193,
 25.38,
 17.33,
 184.6,
 2019,
 0.1622,
 0.6656,
 0.7119,
 0.2654,
 0.4601,
 0.1189)

In [158]:
#  reshape it cuz we are prediting it for single instance

In [159]:
input_data_reshape = ip_array.reshape(1,-1)


# Prediction

In [160]:
prediction = classifire.predict(input_data_reshape)
prediction

if (prediction[0]==0):
    print("The Breast canacer is  means Malignant")

else:
    print("The Breast canacer is means Benign")

The Breast canacer is  means Malignant




---



In [166]:
input_data = (13.54,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.04781,0.1885,0.05766,0.2699,0.7886,2.058,23.56,0.008462,0.0146,0.02387,0.01315,0.0198,0.0023,15.11,19.26,99.7,711.2,0.144,0.1773,0.239,0.1288,0.2977,0.07259)

In [167]:
ip_array = np.asarray(input_data)
input_data

(13.54,
 14.36,
 87.46,
 566.3,
 0.09779,
 0.08129,
 0.06664,
 0.04781,
 0.1885,
 0.05766,
 0.2699,
 0.7886,
 2.058,
 23.56,
 0.008462,
 0.0146,
 0.02387,
 0.01315,
 0.0198,
 0.0023,
 15.11,
 19.26,
 99.7,
 711.2,
 0.144,
 0.1773,
 0.239,
 0.1288,
 0.2977,
 0.07259)

In [168]:
input_data_reshape = ip_array.reshape(1,-1)


In [169]:
prediction = classifire.predict(input_data_reshape)
prediction

if (prediction[0]==0):
    print("The Breast canacer is  means Malignant")

else:
    print("The Breast canacer is means Benign")

The Breast canacer is means Benign




---



---

